name: Static Application Security Testing (SAST) for Go

description: Analyzes Go code for security issues

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - name: Run Gosec Security Scanner
      uses: securego/gosec@master
      with:
        args: "-fmt sarif -out report.sarif ./..."

    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: report.sarif
