name: Scan Image

description: Scan a container image for vulnerabilities

inputs:
  image:
    description: |
      The image to scan.

      Example: `ghcr.io/org/repo/image:tag`
    required: true
  GITHUB_TOKEN:
    description: The GitHub token to use for uploading the scan results
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ inputs.image }}
        format: sarif
        output: trivy-results.sarif
        github-pat: ${{ inputs.GITHUB_TOKEN }}

    - name: Upload scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: trivy-results.sarif
        category: container-scanning
