name: Go Builder and Releaser

description: Build and release Go projects using GoReleaser

inputs:
  go_version_file:
    description: The location of the go.mod file to read the Go version from
    required: false
    default: go.mod
  releaser_args:
    description: Arguments to pass to go releaser
    required: false
    default: release --clean

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        # Required for the changelog to be generated correctly
        fetch-depth: 0
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: ${{ inputs.go_version_file }}

    - name: Run goreleaser
      uses: goreleaser/goreleaser-action@v5
      with:
        version: latest
        args: ${{ inputs.releaser_args }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
