name: Sign Image

description: Sign a container image using cosign.

inputs:
  image:
    description: |
      The image to sign.

      Example: `ghcr.io/org/repo/image:tag`
    required: true
  digest:
    description: The digest of the image to sign.
    required: true

runs:
  using: "composite"
  steps:
    - name: Install cosign
      uses: sigstore/cosign-installer@v3
      with:
        cosign-release: "v2.2.3"
    - name: Sign Image
      shell: bash
      run: |
        cosign sign --key env://COSIGN_KEY --tlog-upload=false ${{ inputs.image }}@${{ inputs.digest }}
      env:
        COSIGN_KEY: ${{ secrets.COSIGN_KEY }}
