name: Go Builder and Releaser

on:
  workflow_call:
    inputs:
      go_version_file:
        description: The location of the go.mod file to read the Go version from
        type: string
        required: false
        default: go.mod
      releaser_args:
        description: Arguments to pass to go releaser
        type: string
        required: false
        default: release --clean

jobs:
  rel:
    name: Build and Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          # Required for the changelog to be generated correctly
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: ${{ github.event.inputs.go_version_file }}
      - name: Run goreleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: ${{ github.event.inputs.releaser_args }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
