# We have a dedicated CI workflow for building and releasing Go projects because
# we're using goreleaser to build and release Go projects.
name: Continuous Integration of a Go project

on:
  workflow_call:
    inputs:
      go_version_file:
        description: Location of the go.mod file to read the Go version from
        type: string
        required: false
        default: go.mod
      go_releaser_config:
        description: Location of the goreleaser configuration file
        type: string
        required: false
        default: .goreleaser.yml
    secrets:
      GPG_PRIVATE_KEY:
        description: GPG private key to sign the release
        required: false
      GPG_PASSPHRASE:
        description: GPG passphrase to sign the release
        required: false

permissions:
  contents: write
  packages: write
  security-events: write

jobs:
  image:
    name: Build, scan & push image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Go
        uses: lvlcn-t/meta/.github/actions/build-go@main
        with:
          go_version_file: ${{ inputs.go_version_file }}
          releaser_args: release --snapshot --clean --config ${{ inputs.go_releaser_config }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

      - name: Get tag ref
        id: version
        run: echo "value=commit-$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Scan Image
        uses: lvlcn-t/meta/.github/actions/scan-image@main
        with:
          image: ghcr.io/${{ github.repository }}:${{ steps.version.outputs.value }}

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image to registry
        run: |
          docker push ghcr.io/${{ github.repository }}:${{ steps.version.outputs.value }}

      - name: Sign image
        uses: lvlcn-t/meta/.github/actions/sign-image@main
        with:
          image: ghcr.io/${{ github.repository }}:${{ steps.version.outputs.value }}
          digest: ${{ github.sha }}
