name: Continuous Integration of Helm Charts

on:
  workflow_call:
    inputs:
      platforms:
        description: The platforms to build for
        type: string
        required: false
        default: linux/amd64,linux/arm64

permissions:
  # Needed to read the contents of the repository
  contents: read
  # Needed to push the image to the container registry
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Get tag ref
        id: version
        run: echo "value=commit-$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Image Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository }}:${{ steps.version.outputs.value }}
          tags: |
            type=ref,event=tag
            type=ref,event=branch
            type=ref,event=pr

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        id: build-push
        with:
          context: .
          platforms: ${{ inputs.platforms}}
          push: false
          tags: |
            ghcr.io/${{ github.repository }}:${{ steps.version.outputs.value }}
            ${{ steps.meta.outputs.tags }}

      - name: Push image to registry
        run: |
          docker push ghcr.io/${{ github.repository }}:${{ steps.version.outputs.value }}

      - name: Scan Image
        uses: lvlcn-t/meta/.github/actions/scan-image@main
        with:
          image: ghcr.io/${{ github.repository }}:${{ steps.version.outputs.value }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
