name: pre-commit.ci

on:
  workflow_dispatch:
    inputs:
      go_version:
        description: "The go version to use"
        required: false
      go_version_file:
        description: "The path to the go version file"
        required: true
        default: "go.mod"

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - uses: actions/setup-go@v5
        if: ${{ inputs.go_version_file }} == ''
        with:
          go-version: ${{ inputs.go_version }}

      - uses: actions/setup-go@v5
        if: ${{ inputs.go_version_file }} != ''
        with:
          go-version-file: ${{ inputs.go_version_file }}

      - name: Install go toolchain for pre-commit
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/HEAD/install.sh | sh -s -- -b $(go env GOPATH)/bin v2.1.5
          go install mvdan.cc/gofumpt@latest

      - uses: pre-commit/action@v3.0.1
        with:
          extra_args: -a
      - uses: pre-commit-ci/lite-action@v1.1.0
        if: always()
        with:
          msg: |
            chore(deps): [pre-commit.ci] auto fixes\n\nFor more information, see https://pre-commit.ci
