name: Release of Helm Charts

on:
  workflow_call:
    inputs:
      chart_location:
        description: The location of the Helm chart to release
        type: string
        required: true

permissions:
  # Needed to read the contents of the repository
  contents: read
  # Needed to push the Helm chart to the GHCR
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to GHCR
        run: |
          helm registry login -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} ghcr.io

      - name: Lint Helm Chart
        run: helm lint ${{ inputs.chart_location }}

      - name: Package Helm Chart
        run: helm package ${{ inputs.chart_location }} -d ./chart

      - name: Push Helm Chart package
        run: helm push $(ls ./chart/*.tgz| head -1) oci://ghcr.io/${{ github.repository }}/charts
