name: Release of a Go project

on:
  workflow_call:
    inputs:
      go_version_file:
        description: Location of the go.mod file to read the Go version from
        type: string
        required: false
        default: go.mod

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build, push and release
        uses: ./.github/actions/build-go.yml@main
        with:
          go_version_file: ${{ github.event.inputs.go_version_file }}
          releaser_args: release --clean

      - name: Get tag
        id: version
        run: echo "tag=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT

      - name: Sign release image
        uses: ./.github/actions/sign-image.yml@main
        with:
          image: ghcr.io/${{ github.event.repository }}:${{ steps.version.outputs.tag }}
          digest: ${{ github.sha }}
