name: Sign Image

on:
  workflow_call:
    inputs:
      image:
        description: |
          The image to sign.

          Example: `ghcr.io/org/repo/image:tag`
        type: string
        required: true
      digest:
        description: The digest of the image to sign.
        type: string
        required: true

jobs:
  sign:
    name: Sign Image
    runs-on: ubuntu-latest
    steps:
      - name: Install cosign
        uses: sigstore/cosign-installer@v3
        with:
          cosign-release: "v2.2.3"
      - name: Sign Image
        run: |
          cosign sign --key env://COSIGN_KEY --tlog-upload=false ${{ github.event.inputs.image }}@${{ github.event.inputs.digest }}
        env:
          COSIGN_KEY: ${{secrets.COSIGN_KEY}}
