name: Test Python

on:
  workflow_call:
    inputs:
      python_version:
        description: Python version to use
        type: string
        required: false
        default: "3.12"
      use_pipenv:
        description: Whether to use pipenv
        type: boolean
        required: false
        default: true
      before_tests:
        description: Commands to run before tests
        type: string
        required: false
      additional_args:
        description: Additional parameters to pass to pytest
        type: string
        required: false

jobs:
  test_python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ inputs.python_version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python_version }}

      - name: Install dependencies w/ pipenv
        if: ${{ inputs.use_pipenv }} == true
        run: |
          python -m pip install --upgrade pip
          pip install --user pipenv
          pipenv install --dev
          pipenv install pytest pytest-custom_exit_code pytest-cov

      - name: Install dependencies w/o pipenv
        if: ${{ inputs.use_pipenv }} == false
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-custom_exit_code pytest-cov

      - name: Run tests
        run: |
          ${{ inputs.before_tests }}
          CMD_PREFIX=""
          if [ ${{ inputs.use_pipenv }} == true ]; then
            CMD_PREFIX="pipenv run"
          fi
          echo "Collecting python tests..."
          TEST_COUNT=$($CMD_PREFIX pytest --collect-only -q | head -n -2 | wc -l) || true
          if [ "$TEST_COUNT" -gt 0 ]; then
            echo "Found $TEST_COUNT python tests, executing them now..."
            $CMD_PREFIX coverage run -m pytest --suppress-no-test-exit-code ${{ inputs.additional_args }}
            $CMD_PREFIX coverage report
            $CMD_PREFIX coverage xml
          else
            echo '<?xml version="1.0" ?>' > coverage.xml
            echo 'Found no python tests, quitting...'
          fi

      - name: Upload coverage report
        uses: 5monkeys/cobertura-action@master
        with:
          path: coverage.xml
          minimum_coverage: 70

  # TODO: add python sast job
