name: Test, Lint and Scan

on:
  workflow_call:
    inputs:
      go_version_file:
        description: Go version to use from go.mod
        type: string
        required: false
      golangci_config:
        description: Path to the golangci config file
        type: string
        required: false
        default: .golangci.yml
      private_go_server:
        description: URL of the private Go server
        type: string
        required: false

      python_version:
        description: Python version to use
        type: string
        required: false
      use_pipenv:
        description: Whether to use pipenv
        type: boolean
        required: false
        default: false

      before_tests:
        description: Commands to run before tests
        type: string
        required: false
      additional_args:
        description: Additional parameters to pass to the test command
        type: string
        required: false
    secrets:
      PRIVATE_GO_SERVER_TOKEN:
        description: Token for the private Go server
        required: false

permissions:
  # Needed if the reusable workflow is used in a private repository
  contents: read
  # Needed for the static analysis result upload
  security-events: write
  # Needed for golangci-lint for the only-new-issues flag
  pull-requests: read
  # Needed to annotate the code with the scan results > https://github.blog/2018-12-14-introducing-check-runs-and-annotations/
  checks: write

jobs:
  go:
    runs-on: ubuntu-latest
    if: inputs.go_version_file != ''
    steps:
      - uses: actions/checkout@v4
      - name: Scan Go
        if: hashFiles('**/*.go') != ''
        uses: lvlcn-t/meta/.github/actions/sast-go@main

      - name: Lint Go
        if: hashFiles('**/*.go') != ''
        uses: lvlcn-t/meta/.github/actions/lint-go@main
        with:
          golangci_config: ${{ inputs.golangci_config }}

      - name: Test Go
        if: hashFiles('**/*.go') != ''
        uses: lvlcn-t/meta/.github/actions/test-go@main
        with:
          go_version_file: ${{ inputs.go_version_file }}
          private_go_server: ${{ inputs.private_go_server }}
          before_tests: ${{ inputs.before_tests }}
          additional_args: ${{ inputs.additional_args }}
        env:
          PRIVATE_GO_SERVER_TOKEN: ${{ secrets.PRIVATE_GO_SERVER_TOKEN }}

  python:
    runs-on: ubuntu-latest
    if: inputs.python_version != ''
    steps:
      - uses: actions/checkout@v4
      # TODO: Uncomment when the actions are ready
      # - name: Lint Python
      #   if: hashFiles('**/*.py') != ''
      #   uses: lvlcn-t/meta/.github/actions/lint-python@main
      #   with:
      #     use_pipenv: "${{ inputs.use_pipenv }}"

      # - name: Scan Python
      #   if: hashFiles('**/*.py') != ''
      #   uses: lvlcn-t/meta/.github/actions/scan-python@main

      - name: Test Python
        if: hashFiles('**/*.py') != ''
        uses: lvlcn-t/meta/.github/actions/test-python@main
        with:
          python_version: ${{ inputs.python_version }}
          use_pipenv: "${{ inputs.use_pipenv }}"
          before_tests: ${{ inputs.before_tests }}
          additional_args: ${{ inputs.additional_args }}
